services:
  docs-tigrcorn-com:
    build: .
    container_name: docs-tigrcorn-com
    restart: unless-stopped
    labels:
      site.host: docs.tigrcorn.com
      site.kind: zdx-docs
    expose:
      - "80"
    networks:
      dockerwp:
        aliases:
          - docs-tigrcorn-com

networks:
  dockerwp:
    name: dockerwp
    external: true
