site_name: Tigrcorn Docs
site_url: https://docs.tigrcorn.com
repo_url: https://github.com/tigrbl/tigrcorn-com
repo_name: tigrbl/tigrcorn-com
copyright: Copyright &copy; 2025 Swarmauri

theme:
  name: material
  palette:
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: orange
      accent: deep purple
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: orange
      accent: deep orange
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  icon:
    repo: fontawesome/brands/github

plugins:
  - search
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          options:
            extensions:
              - griffe_typingdoc
            show_root_heading: true
            show_if_no_docstring: true
            inherited_members: true
            members_order: source
            separate_signature: true
            unwrap_annotated: true
            filters:
              - '!^_'
            merge_init_into_class: true
            docstring_section_style: spacy
            signature_crossrefs: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            show_source: true

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - abbr
  - attr_list
  - pymdownx.snippets
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true
  - tables
  - footnotes

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Guides: guides/index.md
  - Reference: reference/index.md
